// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsjsciwqidpdoudwhuty.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzanNjaXdxaWRwZG91ZHdodXR5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4MDcwMzAsImV4cCI6MjA3MzM4MzAzMH0.XPooaPvNguJEyWH1saE8OtOeEfQ2Sn_18XgbDubeNqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});